# Generated by Django 5.0.1 on 2024-04-09 07:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0003_bookmark"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="usersongrating",
            unique_together={("user", "song")},
        ),
    ]
