# Generated by Django 5.0.1 on 2024-11-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0004_alter_usersongrating_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="NumberOneSong",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("peak_rank", models.IntegerField()),
                ("weeks_on_chart", models.IntegerField()),
                ("average_user_score", models.FloatField(default=0.0)),
                ("total_ratings", models.IntegerField(default=0)),
                ("spotify_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "artist_slug",
                    models.SlugField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "ordering": ["-year"],
                "indexes": [
                    models.Index(fields=["-year"], name="songs_numbe_year_86d988_idx"),
                    models.Index(
                        fields=["artist"], name="songs_numbe_artist_32e94d_idx"
                    ),
                ],
            },
        ),
    ]
