# Generated by Django 5.0.1 on 2025-05-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0005_numberonesong"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrentHot100",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("artist", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("peak_rank", models.IntegerField()),
                ("weeks_on_chart", models.IntegerField()),
                ("current_position", models.IntegerField()),
                ("last_week_position", models.IntegerField(blank=True, null=True)),
                ("position_change", models.IntegerField(blank=True, null=True)),
                ("average_user_score", models.FloatField(default=0.0)),
                ("total_ratings", models.IntegerField(default=0)),
                ("spotify_url", models.URLField(blank=True, null=True)),
                ("youtube_url", models.URLField(blank=True, null=True)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "artist_slug",
                    models.SlugField(blank=True, max_length=255, null=True),
                ),
                ("chart_date", models.DateField()),
            ],
            options={
                "ordering": ["current_position"],
                "indexes": [
                    models.Index(
                        fields=["current_position"],
                        name="songs_curre_current_7a8ff4_idx",
                    ),
                    models.Index(
                        fields=["artist"], name="songs_curre_artist_5e7c2c_idx"
                    ),
                ],
            },
        ),
    ]
