# Generated by Django 5.0.1 on 2025-10-17 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0006_currenthot100"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                (
                    "nationality",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("death_date", models.DateField(blank=True, null=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "artist_type",
                    models.CharField(
                        choices=[
                            ("person", "Person"),
                            ("group", "Group"),
                            ("duo", "Duo"),
                            ("collective", "Collective"),
                        ],
                        default="person",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "musicbrainz_id",
                    models.CharField(blank=True, max_length=36, null=True),
                ),
                ("spotify_id", models.CharField(blank=True, max_length=22, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="artist_images/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="ArtistTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("genre", "Genre"),
                            ("mood", "Mood"),
                            ("style", "Style"),
                            ("instrument", "Instrument"),
                            ("era", "Era"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="artist_fk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="songs",
                to="songs.artist",
            ),
        ),
        migrations.CreateModel(
            name="ArtistRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("member_of", "Member of"),
                            ("solo_from", "Solo artist from"),
                            ("collaboration", "Collaboration"),
                            ("side_project", "Side project"),
                            ("similar", "Similar artist"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                (
                    "from_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_from",
                        to="songs.artist",
                    ),
                ),
                (
                    "to_artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relationships_to",
                        to="songs.artist",
                    ),
                ),
            ],
            options={
                "unique_together": {("from_artist", "to_artist", "relationship_type")},
            },
        ),
        migrations.CreateModel(
            name="ArtistTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("source", models.CharField(max_length=50)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="songs.artist"
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="songs.artisttag",
                    ),
                ),
            ],
            options={
                "unique_together": {("artist", "tag")},
            },
        ),
    ]
