# Generated by Django 5.0.1 on 2025-10-17 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0007_artist_artisttag_song_artist_fk_artistrelationship_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Composition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("original_writer", models.CharField(blank=True, max_length=200)),
                ("original_year", models.IntegerField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="song",
            name="is_original_recording",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="song",
            name="composition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="songs.composition",
            ),
        ),
    ]
