# Generated by Django 5.0.1 on 2025-10-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0008_composition_song_is_original_recording_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="is_traditional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="composition",
            name="musicbrainz_work_id",
            field=models.CharField(blank=True, max_length=36, null=True),
        ),
        migrations.AddField(
            model_name="composition",
            name="verified_source",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
