# Generated by Django 5.0.1 on 2025-10-18 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0009_composition_is_traditional_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="composition",
            name="most_successful_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="most_successful_for",
                to="songs.song",
            ),
        ),
        migrations.AddField(
            model_name="composition",
            name="original_artist",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="composition",
            name="total_versions",
            field=models.IntegerField(default=0),
        ),
    ]
