# Generated by Django 5.0.1 on 2025-10-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0010_composition_most_successful_version_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="image_credit",
            field=models.CharField(
                blank=True,
                help_text='Image source/credit (e.g., "Wikimedia Commons")',
                max_length=500,
            ),
        ),
    ]
