# Generated by Django 5.0.1 on 2025-10-28 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0011_artist_image_credit"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongTimeline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chart_date", models.DateField(db_index=True)),
                ("rank", models.PositiveIntegerField()),
                ("peak_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("weeks_on_chart", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chart_entries",
                        to="songs.song",
                    ),
                ),
            ],
            options={
                "ordering": ["chart_date"],
                "indexes": [
                    models.Index(
                        fields=["chart_date"], name="songs_songt_chart_d_2667d3_idx"
                    ),
                    models.Index(fields=["rank"], name="songs_songt_rank_933bf0_idx"),
                ],
                "unique_together": {("song", "chart_date")},
            },
        ),
    ]
