# Generated by Django 5.0.1 on 2025-11-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0012_songtimeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Public domain artist photo",
                null=True,
                upload_to="artist_images/",
            ),
        ),
    ]
