# Generated by Django 5.0.1 on 2025-11-27 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0013_alter_artist_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SongTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=60, unique=True)),
                (
                    "color",
                    models.CharField(
                        default="#3b82f6",
                        help_text="Hex color code (e.g., #dc2626 for red)",
                        max_length=7,
                    ),
                ),
                (
                    "lucide_icon",
                    models.CharField(
                        blank=True,
                        help_text="Lucide icon name (e.g., snowflake, ghost, heart)",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional: seasonal, theme, novelty, etc.",
                        max_length=30,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description for SEO and tag pages"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Feature this tag on homepage"
                    ),
                ),
                (
                    "display_order",
                    models.IntegerField(
                        default=0, help_text="Lower numbers appear first"
                    ),
                ),
                ("song_count", models.IntegerField(default=0, editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Song Tag",
                "verbose_name_plural": "Song Tags",
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SongTagRelation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("ai", "AI Detection"),
                            ("import", "Data Import"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now_add=True)),
                (
                    "song",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_relations",
                        to="songs.song",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="song_relations",
                        to="songs.songtag",
                    ),
                ),
            ],
            options={
                "ordering": ["tag__display_order"],
                "unique_together": {("song", "tag")},
            },
        ),
        migrations.AddField(
            model_name="song",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="songs",
                through="songs.SongTagRelation",
                to="songs.songtag",
            ),
        ),
    ]
