# Generated by Django 5.0.1 on 2025-11-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0014_songtag_songtagrelation_song_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="songtag",
            name="show_in_actions",
            field=models.BooleanField(
                default=False, help_text="Show this tag in bulk action menu"
            ),
        ),
    ]
