# Generated by Django 5.0.1 on 2025-12-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0015_songtag_show_in_actions"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["title"], name="songs_song_title_2cbace_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["artist"], name="songs_song_artist_4b991e_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["artist_slug"], name="songs_song_artist__f6878b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(fields=["year"], name="songs_song_year_d5825d_idx"),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["peak_rank"], name="songs_song_peak_ra_92ce02_idx"
            ),
        ),
    ]
