# Generated by Django 5.0.1 on 2025-12-17 22:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0016_song_songs_song_title_2cbace_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersongrating",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
