# Generated by Django 5.0.1 on 2025-12-29 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0017_usersongrating_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="songtag",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Hero image for the top of the tag page",
                null=True,
                upload_to="tag_heroes/",
            ),
        ),
    ]
