# Generated by Django 5.0.1 on 2026-01-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0018_songtag_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="tags",
            field=models.ManyToManyField(
                related_name="artists",
                through="songs.ArtistTagRelation",
                to="songs.artisttag",
            ),
        ),
    ]
