# Generated by Django 5.0.1 on 2025-06-06 08:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_charset_to_utf8mb4"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=tinymce.models.HTMLField(),
        ),
    ]
