# Generated by Django 5.0.1 on 2024-03-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordreset"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="PasswordReset",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
