# Generated by Django 5.0.1 on 2026-01-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="points_monthly",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
